### ISSUE TITLE
Storage plugin file errors on Windows

### ISSUE THREAD

**Issue by tecosaur** [tecosaur/DataToolkitCommon.jl#6]
It seems that on windows, an error may be thrown during precompilation at

https://github.com/tecosaur/DataToolkitCommon.jl/blob/8749570b858844a633d7f21242b796ffe8ebf43b/src/store/inventory.jl#L223

The issue seems to be that *somehow* (mysteriously) the cache folder is already created as a file not a folder, leading to a `mkdir` error.

I have absolutely no idea what's going on with this ATM.

**Comment by tecosaur** [comment]
Oh that's interesting, I thought `mkpath` always created a directory, not a file :confused:.

**Comment by chris-b1** [comment]
I don't think it's this `mkpath` itself that's the issue.  If I run the steps @vtfanta outlined above, with an empty `C:\Users\USERNAME\AppData\Local\cache\julia\DataToolkit\`  then `cache` gets created as a folder as expected.   So presumably something earlier in the precompilation process is touching that dir?

**Comment by vtfanta** [comment]
Heh, not for me unfortunately:( With the empty `DataToolkit` I, again, get the `chache` 'file' and the error.

**Comment by chris-b1** [comment]
Hmm, interesting.  I should have noted originally, I *do* get the same precompilation error, but if I manually run those steps `mkpath` makes a path, not a file.

**Comment by vtfanta** [comment]
> So presumably something earlier in the precompilation process is touching that dir?
I think you are correct. When I commented out the initially suspicious lines 232-240 in `inventory.jl` the `cache` file still got created. Now after commenting out the `BaseDirs.User.cache(BaseDirs.Project("DataToolkit"), create=true)` in `Store.jl` it no longer happens, so I think that nails it down to this line.

**Comment by tecosaur** [comment]
The use of a hardcoded `/` instead of something platform-adaptive is so that it can be used in strings and be consistent across all platforms, e.g. `BaseDirs.User.cache(BaseDirs.Project("DataToolkit"), "subfolder/", create=true)`.

I think what needs to be changed here might _just_ be the behaviour when only a project is provided.

**Comment by vtfanta** [comment]
Brilliant! This works on my Win10 :)

**Comment by tecosaur** [comment]
v1.2.2 is now being registered (https://github.com/JuliaRegistries/General/pull/100782), so I think I can (finally) close this :partying_face:
